services:

  github-actions-nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile

    image: github-actions-nodejs-cicd:latest

    container_name: github-actions-nodejs-app

    ports:
      - "3000:3000"

    restart: unless-stopped