name: Deploy Node.js Application to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: ubuntu/ssh-action@v2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: rohan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/rohan/github-actions-nodejs-cicd
            git pull origin main
            docker-compose up -d --build